export enum ErrorCode {
  APPLICATION_NOT_FOUND = 200,
  APPLICATION_INVALID_PROPERTY_KEY = 201,
  APPLICATION_INVALID_PROCESS_ID = 202,
  APPLICATION_OPEN_EXCEPTION = 203,
  APPLICATION_NOT_IN_REGISTRY_EXCEPTION = 204,
  APPLICATION_ALLREADY_RUNNING_EXCEPTION = 205,
  APPLICATION_REGISTRY_COULD_NOT_LOAD_APPLICATIONS = 206
}