export enum ErrorCode {
    COMMAND_ERROR = 1,
    NOT_AUTHORIZED_ERROR = 2,
    NO_PERMISSIONS_ERROR = 3,
    COMMAND_ALLREADY_REGISTERED = 101,
    COMMAND_NOT_REGISTERED = 102,
    SYSTEM_ERROR = 500,
    DOT_ENV_FILE_READ_ERROR = 501
}